//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSONHANVIEN
    {
        public int MAHOSO { get; set; }
        public string TENNHANVIEN { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string VITRI { get; set; }
        public string CCCD { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> MANHANVIEN { get; set; }
    }
}
