//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QlyViecLamEntities1 : DbContext
    {
        public QlyViecLamEntities1()
            : base("name=QlyViecLamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblChucVu> tblChucVu { get; set; }
        public virtual DbSet<tblDanhSachUngTuyen> tblDanhSachUngTuyen { get; set; }
        public virtual DbSet<tblHopDong> tblHopDong { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblPhongBan> tblPhongBan { get; set; }
        public virtual DbSet<tblQuyenHan> tblQuyenHan { get; set; }
        public virtual DbSet<tblTaiKhoan> tblTaiKhoan { get; set; }
        public virtual DbSet<tblThongBao> tblThongBao { get; set; }
        public virtual DbSet<tblThongTinTuyenDung> tblThongTinTuyenDung { get; set; }
    }
}
