//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDanhSachUngTuyen
    {
        public int iMaDanhsach { get; set; }
        public string sMaTD { get; set; }
        public string sMaNV { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblThongTinTuyenDung tblThongTinTuyenDung { get; set; }
    }
}
