//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHopDong
    {
        public string sMaHD { get; set; }
        public Nullable<System.DateTime> dNgayky { get; set; }
        public string sThoihan { get; set; }
        public string sMachucvu { get; set; }
        public string sMaphongban { get; set; }
        public Nullable<int> iLuong { get; set; }
    }
}
