//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoSoNhanVien
    {
        public int iMaHoSoNV { get; set; }
        public string sMaNV { get; set; }
        public string sTenNV { get; set; }
        public string sEmail { get; set; }
        public Nullable<int> iCCCD { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public Nullable<int> iSDT { get; set; }
        public string sDiachi { get; set; }
        public string sHocvan { get; set; }
        public string sKinhnghiem { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
