//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaiKhoan
    {
        public string sMaTK { get; set; }
        public string sMaNV { get; set; }
        public string sMaQuyen { get; set; }
        public string sTaiKhoan { get; set; }
        public string sMatKhau { get; set; }
        public string sTinhTrang { get; set; }
    
        public virtual tblQuyenHan tblQuyenHan { get; set; }
    }
}
