//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongTinTuyenDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblThongTinTuyenDung()
        {
            this.tblDanhSachUngTuyen = new HashSet<tblDanhSachUngTuyen>();
        }
    
        public string sMaTD { get; set; }
        public string sDoituong { get; set; }
        public Nullable<System.DateTime> dNgayyeucau { get; set; }
        public Nullable<System.DateTime> dNgayhethan { get; set; }
        public string sMotaTD { get; set; }
        public Nullable<int> iMucluong { get; set; }
        public string sDaingo { get; set; }
        public string sNoilamviec { get; set; }
        public string sVitri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDanhSachUngTuyen> tblDanhSachUngTuyen { get; set; }
    }
}
