//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThongBao
    {
        public string sMaThongbao { get; set; }
        public string sMaNV { get; set; }
        public Nullable<System.DateTime> dNgayThongbao { get; set; }
        public string sNoidung { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
