//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTaiKhoan()
        {
            this.tblNhanVien = new HashSet<tblNhanVien>();
        }
    
        public string sMaTK { get; set; }
        public string sMaQuyen { get; set; }
        public string sTaiKhoan { get; set; }
        public string sMatKhau { get; set; }
        public string sTinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanVien> tblNhanVien { get; set; }
        public virtual tblQuyenHan tblQuyenHan { get; set; }
    }
}
